<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="wangpengzhideMacBook-Pro.local" ignored="0" name="allTestsInAPackage" tests="3" failures="1" timestamp="30 五月 2023 08:10:01 GMT" time="0.991" errors="0">
  <testcase name="getRequirementListTest001" time="0.91" classname="org.example.AppTest"/>
  <testcase name="loginTest001" time="0.022" classname="org.example.AppTest"/>
  <testcase name="loginTest002" time="0.02" classname="org.example.AppTest">
    <failure type="java.lang.AssertionError" message="expected [10] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [0]
at org.example.AppTest.loginTest002(AppTest.java:43)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- loginTest002 -->
</testsuite> <!-- allTestsInAPackage -->
